import { InjectionToken } from "@angular/core";
import { Observable } from "rxjs";

export type DataType = typeof DATA;

export const DATA_TOKEN = new InjectionToken<Observable<DataType>>('DATA');

export const DATA = [
  {
    "id": "prod-ba39a149",
    "name": "Бальзам-ополаскиватель",
    "brand": "L'Oréal",
    "category": "Уход за волосами",
    "price": 657,
    "currency": "UAH",
    "rating": 4.3,
    "reviews": 149,
    "inStock": false,
    "image": "https://example.com/images/бальзам-ополаскиватель.jpg",
    "description": "Бальзам-ополаскиватель от L'Oréal из категории Уход за волосами. Подходит для ежедневного использования."
  },
  {
    "id": "prod-95c58e0e",
    "name": "Духи",
    "brand": "Schwarzkopf",
    "category": "Парфюмерия",
    "price": 643,
    "currency": "UAH",
    "rating": 4.4,
    "reviews": 57,
    "inStock": false,
    "image": "https://example.com/images/духи.jpg",
    "description": "Духи от Schwarzkopf из категории Парфюмерия. Подходит для ежедневного использования."
  },
  {
    "id": "prod-8f0ab081",
    "name": "Крем для лица",
    "brand": "The Ordinary",
    "category": "Уход за лицом",
    "price": 701,
    "currency": "UAH",
    "rating": 4.3,
    "reviews": 285,
    "inStock": true,
    "image": "https://example.com/images/крем-для-лица.jpg",
    "description": "Крем для лица от The Ordinary из категории Уход за лицом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-d7280337",
    "name": "Тоник",
    "brand": "The Ordinary",
    "category": "Уход за лицом",
    "price": 462,
    "currency": "UAH",
    "rating": 4.9,
    "reviews": 217,
    "inStock": false,
    "image": "https://example.com/images/тоник.jpg",
    "description": "Тоник от The Ordinary из категории Уход за лицом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-92169a10",
    "name": "Губная помада",
    "brand": "Schwarzkopf",
    "category": "Макияж",
    "price": 485,
    "currency": "UAH",
    "rating": 4.7,
    "reviews": 147,
    "inStock": true,
    "image": "https://example.com/images/губная-помада.jpg",
    "description": "Губная помада от Schwarzkopf из категории Макияж. Подходит для ежедневного использования."
  },
  {
    "id": "prod-b2bb880e",
    "name": "Скраб",
    "brand": "Schwarzkopf",
    "category": "Уход за телом",
    "price": 663,
    "currency": "UAH",
    "rating": 4.5,
    "reviews": 142,
    "inStock": false,
    "image": "https://example.com/images/скраб.jpg",
    "description": "Скраб от Schwarzkopf из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-f22642fa",
    "name": "Спрей для объема",
    "brand": "Garnier",
    "category": "Уход за волосами",
    "price": 214,
    "currency": "UAH",
    "rating": 4.6,
    "reviews": 271,
    "inStock": true,
    "image": "https://example.com/images/спрей-для-объема.jpg",
    "description": "Спрей для объема от Garnier из категории Уход за волосами. Подходит для ежедневного использования."
  },
  {
    "id": "prod-083bab25",
    "name": "Тоник",
    "brand": "La Roche-Posay",
    "category": "Уход за лицом",
    "price": 271,
    "currency": "UAH",
    "rating": 4.7,
    "reviews": 218,
    "inStock": true,
    "image": "https://example.com/images/тоник.jpg",
    "description": "Тоник от La Roche-Posay из категории Уход за лицом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-a67f5e37",
    "name": "Тушь для ресниц",
    "brand": "CeraVe",
    "category": "Макияж",
    "price": 506,
    "currency": "UAH",
    "rating": 4.7,
    "reviews": 238,
    "inStock": false,
    "image": "https://example.com/images/тушь-для-ресниц.jpg",
    "description": "Тушь для ресниц от CeraVe из категории Макияж. Подходит для ежедневного использования."
  },
  {
    "id": "prod-ec756933",
    "name": "Крем для рук",
    "brand": "Estée Lauder",
    "category": "Уход за телом",
    "price": 482,
    "currency": "UAH",
    "rating": 4.2,
    "reviews": 177,
    "inStock": false,
    "image": "https://example.com/images/крем-для-рук.jpg",
    "description": "Крем для рук от Estée Lauder из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-85063c11",
    "name": "Дезодорант",
    "brand": "La Roche-Posay",
    "category": "Уход за телом",
    "price": 508,
    "currency": "UAH",
    "rating": 4.4,
    "reviews": 289,
    "inStock": true,
    "image": "https://example.com/images/дезодорант.jpg",
    "description": "Дезодорант от La Roche-Posay из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-1d18562d",
    "name": "Духи",
    "brand": "Maybelline",
    "category": "Парфюмерия",
    "price": 478,
    "currency": "UAH",
    "rating": 4.5,
    "reviews": 75,
    "inStock": true,
    "image": "https://example.com/images/духи.jpg",
    "description": "Духи от Maybelline из категории Парфюмерия. Подходит для ежедневного использования."
  },
  {
    "id": "prod-343c6536",
    "name": "Крем для лица",
    "brand": "The Ordinary",
    "category": "Уход за лицом",
    "price": 168,
    "currency": "UAH",
    "rating": 4.6,
    "reviews": 253,
    "inStock": true,
    "image": "https://example.com/images/крем-для-лица.jpg",
    "description": "Крем для лица от The Ordinary из категории Уход за лицом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-ad72ef58",
    "name": "Гель для душа",
    "brand": "Estée Lauder",
    "category": "Уход за телом",
    "price": 355,
    "currency": "UAH",
    "rating": 5.0,
    "reviews": 213,
    "inStock": true,
    "image": "https://example.com/images/гель-для-душа.jpg",
    "description": "Гель для душа от Estée Lauder из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-a66f91bd",
    "name": "Парфюмированная вода",
    "brand": "Maybelline",
    "category": "Парфюмерия",
    "price": 394,
    "currency": "UAH",
    "rating": 4.9,
    "reviews": 188,
    "inStock": true,
    "image": "https://example.com/images/парфюмированная-вода.jpg",
    "description": "Парфюмированная вода от Maybelline из категории Парфюмерия. Подходит для ежедневного использования."
  },
  {
    "id": "prod-867cb316",
    "name": "Дезодорант",
    "brand": "CeraVe",
    "category": "Уход за телом",
    "price": 515,
    "currency": "UAH",
    "rating": 4.7,
    "reviews": 153,
    "inStock": false,
    "image": "https://example.com/images/дезодорант.jpg",
    "description": "Дезодорант от CeraVe из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-f99e52f1",
    "name": "Крем для рук",
    "brand": "Nivea",
    "category": "Уход за телом",
    "price": 752,
    "currency": "UAH",
    "rating": 4.2,
    "reviews": 285,
    "inStock": true,
    "image": "https://example.com/images/крем-для-рук.jpg",
    "description": "Крем для рук от Nivea из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-285cbdc7",
    "name": "Карандаш для глаз",
    "brand": "Clinique",
    "category": "Макияж",
    "price": 375,
    "currency": "UAH",
    "rating": 4.8,
    "reviews": 113,
    "inStock": true,
    "image": "https://example.com/images/карандаш-для-глаз.jpg",
    "description": "Карандаш для глаз от Clinique из категории Макияж. Подходит для ежедневного использования."
  },
  {
    "id": "prod-329a0036",
    "name": "Дезодорант",
    "brand": "Garnier",
    "category": "Уход за телом",
    "price": 302,
    "currency": "UAH",
    "rating": 4.3,
    "reviews": 271,
    "inStock": true,
    "image": "https://example.com/images/дезодорант.jpg",
    "description": "Дезодорант от Garnier из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-a51673fe",
    "name": "Лосьон для тела",
    "brand": "The Ordinary",
    "category": "Уход за телом",
    "price": 635,
    "currency": "UAH",
    "rating": 4.2,
    "reviews": 87,
    "inStock": true,
    "image": "https://example.com/images/лосьон-для-тела.jpg",
    "description": "Лосьон для тела от The Ordinary из категории Уход за телом. Подходит для ежедневного использования."
  },
  {
    "id": "prod-34e7fc42",
    "name": "Духи",
    "brand": "Nivea",
    "category": "Парфюмерия",
    "price": 692,
    "currency": "UAH",
    "rating": 4.2,
    "reviews": 20,
    "inStock": false,
    "image": "https://example.com/images/духи.jpg",
    "description": "Духи от Nivea из категории Парфюмерия. Подходит для ежедневного использования."
  },
  {
    "id": "prod-15f9f4f1",
    "name": "Карандаш для глаз",
    "brand": "CeraVe",
    "category": "Макияж",
    "price": 685,
    "currency": "UAH",
    "rating": 4.1,
    "reviews": 273,
    "inStock": false,
    "image": "https://example.com/images/карандаш-для-глаз.jpg",
    "description": "Карандаш для глаз от CeraVe из категории Макияж. Подходит для ежедневного использования."
  },
  {
    "id": "prod-394bab5f",
    "name": "Пудра",
    "brand": "Maybelline",
    "category": "Макияж",
    "price": 773,
    "currency": "UAH",
    "rating": 4.2,
    "reviews": 291,
    "inStock": false,
    "image": "https://example.com/images/пудра.jpg",
    "description": "Пудра от Maybelline из категории Макияж. Подходит для ежедневного использования."
  },
  {
    "id": "prod-4188278d",
    "name": "Бальзам-ополаскиватель",
    "brand": "L'Oréal",
    "category": "Уход за волосами",
    "price": 159,
    "currency": "UAH",
    "rating": 4.2,
    "reviews": 171,
    "inStock": false,
    "image": "https://example.com/images/бальзам-ополаскиватель.jpg",
    "description": "Бальзам-ополаскиватель от L'Oréal из категории Уход за волосами. Подходит для ежедневного использования."
  },
  {
    "id": "prod-4333e717",
    "name": "Лосьон для тела",
    "brand": "Nivea",
    "category": "Уход за телом",
    "price": 791,
    "currency": "UAH",
    "rating": 4.7,
    "reviews": 264,
    "inStock": false,
    "image": "https://example.com/images/лосьон-для-тела.jpg",
    "description": "Лосьон для тела от Nivea из категории Уход за телом. Подходит для ежедневного использования."
  }
];
